apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  labels:
    app: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: boardgame
        image: marioud/DevSecOps-boardgame:lts
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
  labels:
    app: game
spec:
  selector:
    app: game
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
