apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  labels:
    app: devsecops-boardgame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops-boardgame
  template:
    metadata:
      labels:
        app: devsecops-boardgame
    spec:
      containers:
      - name: devsecops-boardgame
        image: marioud/devsecops-boardgame:lts
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  selector:
    app: devsecops-boardgame
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
  type: LoadBalancer
