apiVersion: apps/v1
kind: Deployment
metadata:
  name: boardgame-deployment
  labels:
    app: game
spec:
  selector:
    matchLabels:
      app: game
  replicas: 2
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: boardgame
        image: marioud/devsecops-boardgame:lts
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: boardgame-service
spec:
  selector:
    app: game
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
